version: '3.8'
services:
  chat-room-redis:
    image: redis
    container_name: chat-room-redis

  chat-room-postgres:
    image: postgres
    container_name: chat-room-postgres
    environment:
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: chat

  chat-room-server:
    container_name: chat-room-server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    env_file: ./server/.env
    ports:
      - '8080:8080'
    stdin_open: true
    tty: true
    volumes:
      - ./server:/home/user/app
      - /home/user/app/node_modules
    depends_on:
      - chat-room-postgres
      - chat-room-redis

  chat-room-client:
    container_name: chat-room-client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./client/src:/home/user/app/src
      - /home/user/app/node_modules
    stdin_open: true
    tty: true
