FROM node

WORKDIR /home/user/app

COPY package.json .

RUN yarn

RUN npm i -g concurrently

COPY . .

EXPOSE 8080

RUN chown -R node:node /home/user/app

USER node

VOLUME [ "/home/user/app/node_modules" ]

CMD [ "yarn", "dev"]